name: asklora_flutter_test
description: Flutter project as the skeleton for Flutter recruitment test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.5
  equatable: ^2.0.3
  build_runner: ^2.1.8
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
